#!/bin/bash
# Generates BuildInfo.cs with git branch and build date

# Get git branch (fallback to unknown)
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

# Get git commit hash (short)
GIT_COMMIT=$(git log -1 --format=%h 2>/dev/null || echo "unknown")

# Get build date
BUILD_DATE=$(date +"%Y-%m-%d_%H:%M")

# Assembly version passed as argument
ASSEMBLY_VERSION="${1:-2.0.0.0}"

# Output file path from second argument
OUTPUT_FILE="${2:-obj/Debug/net8.0/BuildInfo.cs}"

# Create output directory if needed
mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" <<EOF
// Auto-generated by MSBuild. Do not edit.
namespace TeslaLogger
{
    internal static class BuildInfo
    {
        public const string Version = "${ASSEMBLY_VERSION}";
        public const string GitBranch = "${GIT_BRANCH}";
        public const string GitCommit = "${GIT_COMMIT}";
        public const string BuildDate = "${BUILD_DATE}";
        public const string FullVersion = "-${GIT_BRANCH}-${GIT_COMMIT}-${BUILD_DATE}";
    }
}
EOF

echo "Generated $OUTPUT_FILE (v${ASSEMBLY_VERSION}-${GIT_BRANCH})"