{
 "title": "Ladestatistik",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Car",
    "label": "Fahrzeug",
    "query": "select display_name as __text, id as __value from cars where length(vin) > 5 order by display_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Ladestatistik",
   "type": "table",
   "gridPos": { "h": 15, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select  address, count(*) as Anzahl, max(StartDate) as LetzteLadung, sum(cost_total) as Cost, \r\n(\r\n  select sum(cost_total) / sum(chargingstate.charge_energy_added) as cost\r\n  FROM chargingstate join pos as pos2 on chargingstate.pos = pos2.id join charging on chargingstate.EndChargingID = charging.id\r\n  where pos2.address = T1.address and cost_total is not null and chargingstate.carid=$Car\r\n) as 'Ø Price / kWh', \r\n(\r\n  select sum(chargingstate.charge_energy_added) / sum(cost_kwh_meter_invoice) * 100 as eff\r\n  FROM chargingstate join pos as pos3 on chargingstate.pos = pos3.id join charging on chargingstate.EndChargingID = charging.id and chargingstate.carid=$Car\r\n  where pos3.address = T1.address and cost_kwh_meter_invoice is not null and chargingstate.charge_energy_added <= cost_kwh_meter_invoice\r\n) as 'Eff', \r\nsum(charge_energy_added) as geladen_kWh, avg(charge_energy_added) as avg_geladen_kWh, sum(co2_g_kWh * charge_energy_added / 1000) as \"CO2 kg\" ,sum(charge_energy_added) / sum(MinuteDiff) * 60 as avg_kW, avg(End_battery_level) as AvgSOC, max(End_battery_level) as MaxSOC, sum(MinuteDiff) / 60 as LadezeitStunden, \r\navg(lat) as lat, avg(lng) as lng \r\nfrom \r\n(\r\nSELECT        pos.lat, pos.lng,cost_total, chargingstate.StartDate as StartDate, pos.address, \r\n              chargingstate.charge_energy_added, co2_g_kWh,\r\n              charging_End.ideal_battery_range_km AS EndSOC,\r\n              charging_End.battery_level as End_battery_level,\r\n              TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) as MinuteDiff\r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID INNER JOIN\r\n                         pos ON chargingstate.pos = pos.id \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4  and chargingstate.carid=$Car\r\n) as T1\r\ngroup by address\r\norder by Anzahl desc"
    }
   ]
  },
  {
   "title": "SOC Ladestatistik",
   "type": "table",
   "gridPos": { "h": 12, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(battery_level / 5,0) * 5 as SOC, count(*) as anz FROM chargingstate join charging on chargingstate.EndChargingID = charging.id\nwhere $__timeFilter(StartDate) and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4 and chargingstate.carid=$Car\ngroup by ROUND(battery_level / 5,0) * 5\norder by SOC desc"
    }
   ]
  },
  {
   "title": "SOC Entladestatistik",
   "type": "table",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(battery_level / 5,0) * 5 as SOC, count(*) as Anzahl FROM chargingstate join charging on chargingstate.StartChargingID = charging.id\nwhere $__timeFilter(StartDate) and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4 and chargingstate.carid=$Car\ngroup by ROUND(battery_level / 5,0) * 5\norder by SOC"
    }
   ]
  },
  {
   "title": "Geladen",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT        chargingstate.StartDate as time,chargingstate.charge_energy_added\r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4 and chargingstate.carid=$Car\r\n"
    }
   ]
  },
  {
   "title": "Ladezeit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT        chargingstate.StartDate as time, \r\n              TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) / 60 as HourDiff\r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4 and chargingstate.carid=$Car\r\n"
    }
   ]
  },
  {
   "title": "Anz. Ladungen",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT        chargingstate.StartDate as time,count(*)\r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4 and chargingstate.carid=$Car\r\n"
    }
   ]
  },
  {
   "title": "AC",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(chargingstate.charge_energy_added)\r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID INNER JOIN\r\n                         pos ON chargingstate.pos = pos.id \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and chargingstate.carid=$Car and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4 and\r\n(fast_charger_present = 0 or \r\n(fast_charger_present is null and (address not like '%supercharger%' or address not like '%ionity%') and (charging_End.charge_energy_added / TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) * 60) < 23 )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "DC",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(chargingstate.charge_energy_added)\r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID INNER JOIN\r\n                         pos ON chargingstate.pos = pos.id \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and chargingstate.carid=$Car and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4 and\r\n(fast_charger_present = 1 or \r\n(fast_charger_present is null and address like '%supercharger%') or\r\n(fast_charger_present is null and (charging_End.charge_energy_added / TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) * 60) > 23) \r\n)\r\n"
    }
   ]
  },
  {
   "title": "PV",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(CASE WHEN meter_vehicle_kwh_sum - meter_utility_kwh_sum > 0 THEN meter_vehicle_kwh_sum - meter_utility_kwh_sum else 0 end)\r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID INNER JOIN\r\n                         pos ON chargingstate.pos = pos.id \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and chargingstate.carid=$Car and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4 and\r\n(fast_charger_present = 0 or \r\n(fast_charger_present is null and (address not like '%supercharger%' or address not like '%ionity%') and (charging_End.charge_energy_added / TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) * 60) < 23 )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Ladehub",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT        chargingstate.StartDate as time, \n              charging.battery_level AS 'Start SOC %', \n              charging_End.battery_level as 'End SOC %'\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID \n                         LEFT OUTER JOIN\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\nwhere $__timeFilter(chargingstate.StartDate) and chargingstate.carid=$Car and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4\norder by StartDate desc"
    }
   ]
  },
  {
   "title": "Charging Curves",
   "type": "xychart",
   "gridPos": { "h": 15, "w": 18, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT address, charger_power, charging.battery_level, chargingstate.id as csid\r\nFROM teslalogger.charging \r\njoin chargingstate on charging.id between StartChargingID and EndChargingID \r\njoin pos on chargingstate.Pos = pos.id\r\nWHERE charging.CarID=$Car and $__timeFilter(charging.Datum) and chargingstate.CarID = $Car and $__timeFilter(chargingstate.StartDate) and max_charger_power > 23\r\norder by chargingstate.id, charging.id"
    }
   ]
  },
  {
   "title": "Tesla Supercharger",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(chargingstate.charge_energy_added)\r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID INNER JOIN\r\n                         pos ON chargingstate.pos = pos.id \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4 and \r\naddress like '%supercharger%' and chargingstate.carid=$Car\r\n\r\n"
    }
   ]
  },
  {
   "title": "CCS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(chargingstate.charge_energy_added)\r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID INNER JOIN\r\n                         pos ON chargingstate.pos = pos.id \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4 and\r\n(fast_charger_type = 'Combo') and address not like '%supercharger%' and chargingstate.carid=$Car\r\n"
    }
   ]
  },
  {
   "title": "CHAdeMO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(chargingstate.charge_energy_added)\r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID INNER JOIN\r\n                         pos ON chargingstate.pos = pos.id \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4 and\r\n(fast_charger_type = 'CHAdeMO') and chargingstate.carid=$Car\r\n"
    }
   ]
  },
  {
   "title": "Free SuC Savings",
   "type": "table",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT sum(chargingstate.cost_freesuc_savings_total) as amount, chargingstate.cost_currency as currency\r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID INNER JOIN\r\n                         pos ON chargingstate.pos = pos.id \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and chargingstate.carid=$Car\r\ngroup by chargingstate.cost_currency\r\nhaving amount > 0 and currency is not null\r\norder by amount desc\r\n"
    }
   ]
  },
  {
   "title": "DC Total",
   "type": "stat",
   "description": "Only available with ScanMyTesla",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__time(datum), val \nFROM can\nWHERE $__timeFilter(datum) and id = 11 and carid=$Car\nORDER BY datum DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "AC Total",
   "type": "stat",
   "description": "Only available with ScanMyTesla",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__time(datum), val \nFROM can\nWHERE $__timeFilter(datum) and id = 9 and carid=$Car\nORDER BY datum DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Costs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT chargingstate.StartDate as time, cost_total \r\nFROM chargingstate \r\nwhere $__timeFilter(chargingstate.StartDate) and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 \r\nand EndChargingID - StartChargingID > 4 and carid=$Car\r\nand (cost_currency in ('eur','€','',' ') or isnull(cost_currency))\r\n"
    }
   ]
  },
  {
   "title": "€/kWh",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT max(chargingstate.StartDate) as time ,sum(cost_total) / sum(chargingstate.charge_energy_added) as value\r\nFROM chargingstate \r\njoin charging on chargingstate.EndChargingID = charging.id\r\nwhere $__timeFilter(chargingstate.StartDate) and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 \r\nand EndChargingID - StartChargingID > 4 and chargingstate.carid=$Car\r\nand (cost_currency in ('eur','€','',' ') or isnull(cost_currency))\r\n"
    }
   ]
  },
  {
   "title": "Costs unspecified",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT        chargingstate.StartDate as time,charging_End.charge_energy_added\r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4 and chargingstate.carid=$Car\r\nand isnull(cost_total)\r\n"
    }
   ]
  }
 ]
}