{
 "title": "Position all cars",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 22, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(pos.datum) as time_sec, lat, lng, 3 as type, \r\nconcat('<a href=\"/d/zm7wN6Zgz/verbrauch?orgId=1&var-Car=', pos.carid,'\"><b>Online:</b></a>', IFNULL(display_name,'') ,'<br>',IFNULL(battery_level,0), '% SOC <br>', IFNULL(address,'')) as address FROM pos \r\njoin cars on pos.carid = cars.id\r\njoin (SELECT max(id) as id FROM pos group by carid) as p2 on p2.id = pos.id\r\njoin (select carid from state where enddate is null and state = 'online') as state on state.carid = pos.CarID\r\nunion\r\nSELECT UNIX_TIMESTAMP(pos.datum) as time_sec, lat, lng, 2 as type, \r\nconcat('<a href=\"/d/zm7wN6Zgz/verbrauch?orgId=1&var-Car=', pos.carid,'\"><b>Fahren:</b></a>', IFNULL(display_name,'') ,'<br>',IFNULL(battery_level,0), '% SOC <br>', speed, ' km/h') as address FROM pos \r\njoin cars on pos.carid = cars.id\r\njoin (SELECT max(id) as id FROM pos group by carid) as p2 on p2.id = pos.id\r\njoin (select carid from drivestate where enddate is null) as state on state.carid = pos.CarID\r\nunion\r\nSELECT UNIX_TIMESTAMP(pos.datum) as time_sec, lat, lng, 1 as type, \r\nconcat('<a href=\"/d/BHhxFeZRz/laden?orgId=1&var-Car=', pos.carid,'\"><b>Laden:</b></a>', IFNULL(display_name,'') ,'<br>',IFNULL(battery_level,0), '% SOC <br>', power * -1, ' kW') as address FROM pos \r\njoin cars on pos.carid = cars.id\r\njoin (SELECT max(id) as id FROM pos group by carid) as p2 on p2.id = pos.id\r\njoin (select carid from chargingstate where enddate is null) as state on state.carid = pos.CarID\r\nunion\r\nSELECT UNIX_TIMESTAMP(pos.datum) as time_sec, lat, lng, 4 as type, \r\nconcat('<a href=\"/d/zm7wN6Zgz/verbrauch?orgId=1&var-Car=', pos.carid,'\"><b>Schlafen:</b></a>', IFNULL(display_name,'') ,'<br>',IFNULL(battery_level,0), '% SOC <br>', IFNULL(address,'')) as address FROM pos \r\njoin cars on pos.carid = cars.id\r\njoin (SELECT max(id) as id FROM pos group by carid) as p2 on p2.id = pos.id\r\njoin (select carid from state where enddate is null and state in ('offline','asleep')) as state on state.carid = pos.CarID\r\n"
    }
   ]
  },
  {
   "title": "Cars",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "select count(*) from cars" }
   ]
  },
  {
   "title": "Charging",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM chargingstate where endDate is null "
    }
   ]
  },
  {
   "title": "Driving",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM drivestate where endDate is null "
    }
   ]
  },
  {
   "title": "Sleeping",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM state where state in ('asleep','offline') and enddate is null"
    }
   ]
  }
 ]
}