{
 "title": "Status",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Car",
    "label": "Fahrzeug",
    "query": "select display_name as __text, id as __value from cars where length(vin) > 5 order by display_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select \ncase\n  WHEN status = 1 then 'Sleep'\n  WHEN status = 2 then 'Online'\n  WHEN status = 3 then 'Offline'\n  WHEN status = 4 then 'Waking'\n  WHEN status = 5 then '?'\n  WHEN status = 6 then 'Driving'\n  WHEN status = 7 then 'Charging'\nend\n\nfrom (\nSELECT $__time(StartDate), \n(case \n\tWHEN state = 'asleep' then 1 \n\tWHEN state = 'online' then 2 \n    WHEN state = 'offline' then 3 \n    WHEN state = 'waking' then 4 \n    else 5 \nend) as status\nFROM state \nWHERE  \n$__timeFilter(startdate) and carid=$Car \n\nunion\nSELECT $__time(StartDate), 6 as status FROM trip WHERE $__timeFilter(StartDate) and carid=$Car \nunion \nSELECT $__time(EndDate), 2 as status FROM trip WHERE $__timeFilter(StartDate) and carid=$Car  and EndDate IS NOT NULL /* end of trip is online */\n\nunion\nSELECT $__time(StartDate), 7 as status FROM chargingstate WHERE $__timeFilter(StartDate) and carid=$Car  \nunion\nSELECT $__time(EndDate), 2 as status FROM chargingstate WHERE $__timeFilter(StartDate) and carid=$Car  and EndDate IS NOT NULL  /* end of charging is online */\n\norder by time_sec desc\n) as t1\nLimit 1\n"
    }
   ]
  },
  {
   "title": "SOC",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select battery_level\r\nFROM\r\n(\r\nSELECT $__time(datum),battery_level\r\nFROM  pos\r\nWHERE  $__timeFilter(datum) and carid=$Car \r\nunion\r\nSELECT $__time(datum),battery_level\r\nFROM  charging\r\nWHERE  $__timeFilter(datum) and carid=$Car \r\norder by time_sec desc\r\n) as t1\r\nLimit 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Reichweite",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select ideal_battery_range_km\r\nFROM\r\n(\r\nSELECT $__time(datum),ideal_battery_range_km\r\nFROM  pos\r\nWHERE  $__timeFilter(datum) and carid=$Car \r\nunion\r\nSELECT $__time(datum),ideal_battery_range_km\r\nFROM  charging\r\nWHERE  $__timeFilter(datum) and carid=$Car \r\norder by time_sec desc\r\n) as t1\r\nLimit 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Außentemperatur",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select outside_temp\r\nFROM\r\n(\r\nSELECT $__time(datum),outside_temp\r\nFROM  pos\r\nWHERE  $__timeFilter(datum) and carid=$Car \r\nunion\r\nSELECT $__time(datum),outside_temp\r\nFROM  charging\r\nWHERE  $__timeFilter(datum) and carid=$Car \r\norder by time_sec desc\r\n) as t1\r\nLimit 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Zelltemperatur",
   "type": "gauge",
   "description": "Nur verfügbar mit ScanMyTesla oder Fleet API",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select * FROM \n(\n    SELECT val as 'Cell Temperature', datum\n    FROM can\n    WHERE $__timeFilter(datum) and carid=$Car  and id = 2 and datum > \n    (\n        SELECT $__time(StartDate)\n        FROM state \n        WHERE  \n        $__timeFilter(startdate) and carid=$Car \n        \n        union\n        SELECT $__time(StartDate) FROM trip WHERE $__timeFilter(StartDate) and carid=$Car \n        union \n        SELECT $__time(EndDate) FROM trip WHERE $__timeFilter(StartDate) and carid=$Car  and EndDate IS NOT NULL /* end of trip is online */\n        \n        union\n        SELECT $__time(StartDate) FROM chargingstate WHERE $__timeFilter(StartDate) and carid=$Car  \n        union\n        SELECT $__time(EndDate) FROM chargingstate WHERE $__timeFilter(StartDate) and carid=$Car  and EndDate IS NOT NULL  /* end of charging is online */\n        \n        order by time_sec desc\n        Limit 1\n    )\n    union\n    SELECT moduleTempMin as 'Cell Temperature', date as datum FROM battery where carid = $Car and $__timeFilter(date) and moduleTempMin is not null and date > \n    (\n        SELECT $__time(StartDate)\n        FROM state \n        WHERE  \n        $__timeFilter(startdate) and carid=$Car \n        \n        union\n        SELECT $__time(StartDate) FROM trip WHERE $__timeFilter(StartDate) and carid=$Car \n        union \n        SELECT $__time(EndDate) FROM trip WHERE $__timeFilter(StartDate) and carid=$Car  and EndDate IS NOT NULL /* end of trip is online */\n        \n        union\n        SELECT $__time(StartDate) FROM chargingstate WHERE $__timeFilter(StartDate) and carid=$Car  \n        union\n        SELECT $__time(EndDate) FROM chargingstate WHERE $__timeFilter(StartDate) and carid=$Car  and EndDate IS NOT NULL  /* end of charging is online */\n        \n        order by time_sec desc\n        Limit 1\n)\n) a\norder by datum\n"
    }
   ]
  },
  {
   "title": "Odometer",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT odometer\r\nFROM  pos\r\nWHERE  $__timeFilter(datum) and carid=$Car \r\nORDER BY  id DESC \r\nLimit 1"
    }
   ]
  },
  {
   "title": "TPMS FL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pressure as text FROM TPMS where carid=$Car and TireId = 1 order by Datum desc limit 1"
    }
   ]
  },
  {
   "title": "TPMS FR",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pressure as text FROM TPMS where carid=$Car and TireId = 2 order by Datum desc limit 1"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__time(StartDate), \n(case \n\tWHEN state = 'asleep' then 1 \n\tWHEN state = 'online' then 2 \n    WHEN state = 'offline' then 3 \n    WHEN state = 'waking' then 4 \n    else 5 \nend) as status\nFROM state \nWHERE  \n$__timeFilter(startdate) and carid=$Car \n\nunion\nSELECT $__time(StartDate), 6 as status FROM trip WHERE $__timeFilter(StartDate) and carid=$Car \nunion \nSELECT $__time(EndDate), 2 as status FROM trip WHERE $__timeFilter(StartDate) and carid=$Car  and EndDate IS NOT NULL /* end of trip is online */\n\nunion\nSELECT $__time(StartDate), 7 as status FROM chargingstate WHERE $__timeFilter(StartDate) and carid=$Car  \nunion\nSELECT $__time(EndDate), 2 as status FROM chargingstate WHERE $__timeFilter(StartDate) and carid=$Car  and EndDate IS NOT NULL  /* end of charging is online */\n\norder by time_sec desc\nLimit 1"
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT LEFT(version, CHAR_LENGTH(version) - LOCATE(' ', REVERSE(version))) as text FROM car_version where carid=$Car order by id desc limit 1"
    }
   ]
  },
  {
   "title": "TPMS RL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pressure as text FROM TPMS where carid=$Car and TireId = 3 order by Datum desc limit 1"
    }
   ]
  },
  {
   "title": "TPMS RR",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pressure as text FROM TPMS where carid=$Car and TireId = 4 order by Datum desc limit 1"
    }
   ]
  },
  {
   "title": "Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT $__time(StartDate), \n(case \n\tWHEN state = 'asleep' then 1 \n\tWHEN state = 'online' then 2 \n    WHEN state = 'offline' then 3 \n    WHEN state = 'waking' then 4 \n    else 5 \nend) as status\nFROM state \nWHERE  \n$__timeFilter(startdate) and carid=$Car \n\nunion\nSELECT $__time(StartDate), 6 as status FROM trip WHERE $__timeFilter(StartDate) and carid=$Car \nunion \nSELECT $__time(EndDate), 2 as status FROM trip WHERE $__timeFilter(StartDate) and carid=$Car  and EndDate IS NOT NULL /* end of trip is online */\n\nunion\nSELECT $__time(StartDate), 7 as status FROM chargingstate WHERE $__timeFilter(StartDate)  and carid=$Car \nunion\nSELECT $__time(EndDate), 2 as status FROM chargingstate WHERE $__timeFilter(StartDate) and carid=$Car  and EndDate IS NOT NULL  /* end of charging is online */\n\norder by time_sec\n"
    }
   ]
  }
 ]
}