{
 "title": "Verbrauch",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Car",
    "label": "Fahrzeug",
    "query": "select display_name as __text, id as __value from cars where length(vin) > 5 order by display_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Verbrauch",
   "type": "graph",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   $__time(datum),  speed as 'Geschwindigkeit [km/h]',   power as 'Leistung [PS]',   ideal_battery_range_km as 'Reichweite [km]', battery_level as 'SOC [%]',  outside_temp as 'Außentemperatur [°C]',  altitude as 'Höhe [m]', inside_temp as 'Innentemperatur [°C]', \r\nbattery_heater * 100 as 'Battery Heater',\r\nis_preconditioning * 100 as 'Preconditioning',\r\nsentry_mode * 100 as 'Sentry Mode',\r\nodometer -  (select min(odometer) from pos WHERE  $__timeFilter(datum) and CarID = $Car) as km\r\n\r\nFROM  pos\r\nWHERE  $__timeFilter(datum) and CarID = $Car\r\nORDER BY  Datum ASC"
    },
    {
     "rawSql": "SELECT $__time(datum), val as 'Zelltemperatur [°C]'\nFROM can\nWHERE $__timeFilter(datum) and id = 2 and CarID = $Car and val between -50 and 100\nORDER BY datum ASC"
    },
    {
     "rawSql": "SELECT $__time(datum), val as 'Cell imbalance [mV]'\nFROM can\nWHERE $__timeFilter(datum) and id = 27 and CarID = $Car and val between 0 and 3000\nORDER BY datum ASC\n"
    },
    {
     "rawSql": "SELECT $__time(datum), val as 'BMS max charge [kW]'\nFROM can\nWHERE $__timeFilter(datum) and id = 28 and CarID = $Car  and val between 0 and 300\nORDER BY datum ASC"
    },
    {
     "rawSql": "SELECT $__time(datum), val as 'BMS max discharge [kW]'\nFROM can\nWHERE $__timeFilter(datum) and id = 29 and CarID = $Car and val between 0 and 600\nORDER BY datum ASC"
    },
    {
     "rawSql": "SELECT $__time(datum), val as 'Cell min [v]'\nFROM can\nWHERE $__timeFilter(datum) and id = 5 and CarID = $Car  and val between 2 and 4.5\nORDER BY datum ASC"
    },
    {
     "rawSql": "SELECT $__time(date), ModuleTempMin FROM battery WHERE $__timeFilter(date) and CarID = $Car and ModuleTempMin is not null"
    }
   ]
  },
  {
   "title": "Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(datum),\r\n   lat,\r\n   lng,\r\n   0 as type,\r\n   null as address,\r\n   ap\r\n   FROM pos\r\nWHERE  $__timeFilter(datum) and carid = $Car\r\nUNION\r\n  SELECT UNIX_TIMESTAMP(pos.datum) as time_sec, lat, lng, 1 as type, concat('<b>',address, '</b><br>Date: ',pos.datum, '<br>Duration: ', TIMESTAMPDIFF(MINUTE, StartDate, EndDate) ,'min<br>Charged: ',charging.charge_energy_added, 'kWh<br>Max Power:', max_charger_power, 'kW') as address, 0 as ap FROM chargingstate join charging on endchargingid = charging.id join pos on chargingstate.Pos = pos.id\r\n  WHERE $__timeFilter(pos.datum) and chargingstate.CarID = $Car and (fast_charger_brand = 'Tesla' or address like '%Supercharger%')\r\nUNION\r\n  SELECT UNIX_TIMESTAMP(pos.datum) as time_sec, lat, lng, \r\n  CASE \r\n    WHEN address LIKE '%ENBW%' THEN 6 \r\n    WHEN address LIKE '%Ionity%' THEN 5 \r\n    ELSE 2 \r\n  END as type, concat('<b>',address, '</b><br>Date: ',pos.datum, '<br>Duration: ', TIMESTAMPDIFF(MINUTE, StartDate, EndDate) ,'min<br>Charged: ',charging.charge_energy_added, 'kWh<br>Max Power:', max_charger_power, 'kW') as address, 0 as ap FROM chargingstate join charging on endchargingid = charging.id join pos on chargingstate.Pos = pos.id\r\n  WHERE $__timeFilter(pos.datum) and chargingstate.CarID = $Car \r\n  and (max_charger_power > 25 and address not like '%supercharger%')\r\nUNION\r\n  SELECT UNIX_TIMESTAMP(pos.datum) as time_sec, lat, lng, 3 as type, concat('<b>',address, '</b><br>Date: ',pos.datum, '<br>Duration: ', TIMESTAMPDIFF(MINUTE, StartDate, EndDate) ,'min<br>Charged: ',charging.charge_energy_added, 'kWh<br>Max Power:', max_charger_power, 'kW') as address, 0 as ap FROM chargingstate join charging on endchargingid = charging.id join pos on chargingstate.Pos = pos.id\r\n  WHERE $__timeFilter(pos.datum) and chargingstate.CarID = $Car and  max_charger_power < 25 and address not like '%supercharger%'\r\nUNION\r\n  SELECT UNIX_TIMESTAMP(T1.time_sec) as time_sec, lat, lng, 4 as type, concat('<b>', address,'</b><br>Date: ',T1.time_sec, '<br>Duration: ', TIMESTAMPDIFF(MINUTE,T1.time_sec, T2.time_sec), 'min'), 0 as ap  FROM (\r\n    SELECT @rowid:=@rowid+1 as rowid, drivestate.EndDate as time_sec, lat, lng, 4 as type, address \r\n    FROM drivestate join pos on drivestate.EndPos = pos.id, (SELECT @rowid:=0) as init\r\n    WHERE $__timeFilter(drivestate.EndDate) and drivestate.CarID = $Car \r\n    ) T1 join \r\n    (\r\n    SELECT @rowid2:=@rowid2+1 as rowid, drivestate.StartDate as time_sec \r\n    FROM drivestate join pos on drivestate.EndPos = pos.id, (SELECT @rowid2:=0) as init\r\n    WHERE $__timeFilter(drivestate.EndDate) and drivestate.CarID = $Car \r\n    ) T2 on T1.rowid+1=T2.rowid\r\n\r\n ORDER BY time_sec ASC"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT speed div 10 * 10 as kmh, count(*) / (select count(*) from pos where $__timeFilter(datum) and CarID = $Car) as total\r\nFROM pos \r\nwhere $__timeFilter(datum) and CarID = $Car\r\ngroup by speed div 10 \r\nhaving kmh >= 0"
    }
   ]
  }
 ]
}