{
 "title": "Degradation",
 "time": { "from": "now-30M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Car",
    "label": "Car",
    "query": "select display_name as __text, id as __value from cars where length(vin) > 5 order by display_name"
   },
   { "name": "SOC", "label": "Min Charging SOC", "query": "100,90,80,70,60,50,40,30,20,10" }
  ]
 },
 "panels": [
  {
   "title": "Degradation",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT        $__time(chargingstate.StartDate), \r\n              charging_End.ideal_battery_range_km / charging_End.battery_level* 100  as 'Maximalreichweite [km]',\r\n              pos.odometer as 'km Stand [km]'\r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID INNER JOIN\r\n                         pos ON chargingstate.pos = pos.id \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and pos.odometer > 1 and charging_End.battery_level >= $SOC and chargingstate.CarID = $Car \r\norder by chargingstate.StartDate\r\n"
    },
    {
     "rawSql": "SELECT $__time(datum), val as 'Nominal full pack [kWh]' FROM can WHERE $__timeFilter(datum) and id = 71 and val > 30 and val < 110 and CarID = $Car  ORDER BY datum ASC"
    },
    {
     "rawSql": "SELECT  $__time(chargingstate.StartDate), \r\n        AVG(charging_End.ideal_battery_range_km / charging_End.battery_level * 100) AS 'Max. Reichweite (Monatsmittel) [km]'\r\nFROM charging \r\nINNER JOIN chargingstate ON charging.id = chargingstate.StartChargingID\r\nINNER JOIN pos ON chargingstate.pos = pos.id \r\nLEFT OUTER JOIN charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nWHERE $__timeFilter(chargingstate.StartDate) \r\n  AND TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and pos.odometer > 1 and chargingstate.CarID = $Car \r\nGROUP BY EXTRACT(YEAR_MONTH FROM chargingstate.StartDate)\r\norder by charging.Datum"
    },
    {
     "rawSql": "SELECT $__time(datum), val as 'Energy Buffer [kWh]' FROM can WHERE $__timeFilter(datum) and id = 87 and CarID = $Car  ORDER BY datum ASC"
    },
    {
     "rawSql": "SELECT $__time(datum), val as 'SOH [%]' FROM can WHERE $__timeFilter(datum) and id = 1000 and CarID = $Car  ORDER BY datum ASC"
    }
   ]
  },
  {
   "title": "Cell Inbalance",
   "type": "timeseries",
   "description": "Data is only available if you use Fleet API and installed a virtual key. Old Model S/X (pre 2021) are not supported!",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "rawSql": "SELECT $__time(date), (BrickVoltageMax - BrickVoltageMin) * 1000 as 'Cell Inbalance'  FROM teslalogger.battery where CarID = $Car and $__timeFilter(date) and BrickVoltageMax is not null and brickvoltagemin is not null"
    }
   ]
  },
  {
   "title": "Cell number with the lowest voltages",
   "type": "table",
   "description": "Data is only available if you use Fleet API and installed a virtual key. Old Model S/X (pre 2021) are not supported!",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT NumBrickVoltageMin as Cell, count(*) as cnt  FROM battery \r\nwhere NumBrickVoltageMin is not null and CarID = $Car and $__timeFilter(date)\r\ngroup by NumBrickVoltageMin\r\norder by cnt desc"
    }
   ]
  },
  {
   "title": "Cell number with the highest voltages",
   "type": "table",
   "description": "Data is only available if you use Fleet API and installed a virtual key. Old Model S/X (pre 2021) are not supported!",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT NumBrickVoltageMax as Cell, count(*) as cnt  FROM battery \r\nwhere NumBrickVoltageMax is not null and CarID = $Car and $__timeFilter(date)\r\ngroup by NumBrickVoltageMax\r\norder by cnt desc"
    }
   ]
  }
 ]
}