{
 "title": "Journey",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Car",
    "label": "Fahrzeug",
    "query": "select display_name as __text, id as __value from cars where length(vin) > 5 order by display_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 23, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(datum),\r\n   lat,\r\n   lng,\r\n   0 as type,\r\n   null as address,\r\n   ap\r\n   FROM pos\r\nWHERE  $__timeFilter(datum) and carid = $Car\r\nUNION\r\n  SELECT UNIX_TIMESTAMP(pos.datum) as time_sec, lat, lng, 1 as type, concat('<b>',address, '</b><br>Date: ',pos.datum, '<br>Duration: ', TIMESTAMPDIFF(MINUTE, StartDate, EndDate) ,'min<br>Charged: ',charging.charge_energy_added, 'kWh<br>Max Power:', max_charger_power, 'kW') as address, 0 as ap FROM chargingstate join charging on endchargingid = charging.id join pos on chargingstate.Pos = pos.id\r\n  WHERE $__timeFilter(pos.datum) and chargingstate.CarID = $Car and (fast_charger_brand = 'Tesla' or address like '%Supercharger%')\r\nUNION\r\n  SELECT UNIX_TIMESTAMP(pos.datum) as time_sec, lat, lng, 2 as type, concat('<b>',address, '</b><br>Date: ',pos.datum, '<br>Duration: ', TIMESTAMPDIFF(MINUTE, StartDate, EndDate) ,'min<br>Charged: ',charging.charge_energy_added, 'kWh<br>Max Power:', max_charger_power, 'kW') as address, 0 as ap FROM chargingstate join charging on endchargingid = charging.id join pos on chargingstate.Pos = pos.id\r\n  WHERE $__timeFilter(pos.datum) and chargingstate.CarID = $Car \r\n  and ((fast_charger_brand is not null && fast_charger_brand not in ('Tesla') and fast_charger_present = 1 and address not like '%supercharger%') \r\n  or (fast_charger_present is null and max_charger_power > 25 and address not like '%supercharger%'))\r\nUNION\r\n  SELECT UNIX_TIMESTAMP(pos.datum) as time_sec, lat, lng, 3 as type, concat('<b>',address, '</b><br>Date: ',pos.datum, '<br>Duration: ', TIMESTAMPDIFF(MINUTE, StartDate, EndDate) ,'min<br>Charged: ',charging.charge_energy_added, 'kWh<br>Max Power:', max_charger_power, 'kW') as address, 0 as ap FROM chargingstate join charging on endchargingid = charging.id join pos on chargingstate.Pos = pos.id\r\n  WHERE $__timeFilter(pos.datum) and chargingstate.CarID = $Car and ((fast_charger_present = 0) or (fast_charger_present is null and max_charger_power < 25 and address not like '%supercharger%'))\r\nUNION\r\n  SELECT UNIX_TIMESTAMP(T1.time_sec) as time_sec, lat, lng, 4 as type, concat('<b>', address,'</b><br>Date: ',T1.time_sec, '<br>Duration: ', TIMESTAMPDIFF(MINUTE,T1.time_sec, T2.time_sec), 'min'), 0 as ap  FROM (\r\n\t    SELECT @rowid:=@rowid+1 as rowid, drivestate.EndDate as time_sec, lat, lng, 4 as type, address \r\n\t    FROM drivestate join pos on drivestate.EndPos = pos.id, (SELECT @rowid:=0) as init\r\n\t    WHERE $__timeFilter(drivestate.EndDate) and drivestate.CarID = $Car \r\n    ) T1 join \r\n    (\r\n\t    SELECT @rowid2:=@rowid2+1 as rowid, drivestate.StartDate as time_sec \r\n\t    FROM drivestate join pos on drivestate.EndPos = pos.id, (SELECT @rowid2:=0) as init\r\n\t    WHERE $__timeFilter(drivestate.EndDate) and drivestate.CarID = $Car \r\n    ) T2 on T1.rowid+1=T2.rowid\r\n\r\n ORDER BY time_sec ASC"
    }
   ]
  },
  {
   "title": "Charging",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT       \r\n  sum(chargingstate.charge_energy_added) as kWh,\r\n  sum(case WHEN fast_charger_present = 1 or max_charger_power > 23 then chargingstate.charge_energy_added else null END) as kWhDC,\r\n  sum(case WHEN fast_charger_present = 1 or max_charger_power > 23 then NULL else chargingstate.charge_energy_added END) as kWhAC,\r\n\r\n  sum(chargingstate.charge_energy_added) / (SELECT max(odometer) - min(odometer) FROM pos WHERE  $__timeFilter(datum) and carid = $Car) * 100 as Consumption100km,\r\n  sum(case WHEN fast_charger_present = 1 or max_charger_power > 23 then TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) else null END) as MinutesDC,\r\n  min(case WHEN fast_charger_present = 1 or max_charger_power > 23 then TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) else null END) as MinMinutesDC,\r\n  avg(case WHEN fast_charger_present = 1 or max_charger_power > 23 then TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) else null END) as AVGMinutesDC,\r\n  max(case WHEN fast_charger_present = 1 or max_charger_power > 23 then TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) else null END) as MaxMinutesDC,\r\n  sum(case WHEN fast_charger_present = 1 or max_charger_power > 23 then 1 else 0 END) as CountDC,\r\n  sum(case WHEN fast_charger_present = 1 or max_charger_power > 23 then null else TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) END) as MinutesAC,\r\n  sum(case WHEN fast_charger_present = 1 or max_charger_power > 23 then 0 else 1 END) as CountAC,\r\n  sum(TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate)) as MinuteDiff         \r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and chargingstate.EndChargingID - chargingstate.StartChargingID > 2\r\nand chargingstate.CarId = $Car \r\norder by StartDate desc"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT       \r\n  sum(cost_total) as Total,\r\n  sum(cost_total) / (SELECT max(odometer) - min(odometer) FROM pos WHERE  $__timeFilter(datum) and carid = $Car) * 100 as Cost100km,\r\n  sum(cost_total) / sum(chargingstate.charge_energy_added) as avgCostkWh,\r\n  sum(case WHEN fast_charger_present = 1 or max_charger_power > 23 then cost_total else 0 end) / \r\n  sum(case WHEN fast_charger_present = 1 or max_charger_power > 23 then chargingstate.charge_energy_added  else 0 end) as avgCostkWhDC,\r\n  min(case WHEN fast_charger_present = 1 or max_charger_power > 23 then cost_total / chargingstate.charge_energy_added else null end) minCostkWhDC,\r\n  max(case WHEN fast_charger_present = 1 or max_charger_power > 23 then cost_total / chargingstate.charge_energy_added else null end) maxCostkWhDC,\r\n  sum(case WHEN fast_charger_present = 1 or max_charger_power > 23 then 0 else cost_total end) / \r\n  sum(case WHEN fast_charger_present = 1 or max_charger_power > 23 then 0 else chargingstate.charge_energy_added end) as avgCostkWhAC,\r\n  min(case WHEN fast_charger_present = 1 or max_charger_power > 23 then null else cost_total / chargingstate.charge_energy_added end) minCostkWhAC,\r\n  max(case WHEN fast_charger_present = 1 or max_charger_power > 23 then null else cost_total / chargingstate.charge_energy_added end) maxCostkWhAC\r\n  \r\nFROM            charging inner JOIN chargingstate ON charging.id = chargingstate.StartChargingID \r\n                         LEFT OUTER JOIN\r\n                         charging AS charging_End ON chargingstate.EndChargingID = charging_End.id\r\nwhere $__timeFilter(chargingstate.StartDate) and chargingstate.EndChargingID - chargingstate.StartChargingID > 2\r\nand chargingstate.CarId = $Car \r\norder by StartDate desc"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT \n  round((SELECT max(odometer) - min(odometer) FROM pos WHERE  $__timeFilter(datum) and carid = $Car),1) as kmDriven,\n  max(speed_max) as speed_max, max(power_max) as power_max, (select sum(km_diff) / sum(DurationMinutes) * 60) as avg_kmh\nfrom trip WHERE \n  $__timeFilter(StartDate) and km_diff < 1000 and CarID = $Car \norder by StartDate desc\n"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \n    max(EndOdometer - StartOdometer) AS maxKmDrivenPerCharge,\n    max((EndOdometer - StartOdometer) / (StartSOC - EndSOC) * 100) AS MaxCalculatedRangePerCharge,\n    (SELECT max(km_diff) from trip WHERE $__timeFilter(StartDate) and km_diff < 1000 and CarID = $Car ) as maxTripKm,\n    (SELECT min(km_diff) from trip WHERE $__timeFilter(StartDate) and km_diff < 1000 and CarID = $Car and km_diff > 10) as minTripKm,\n    (SELECT avg(km_diff) from trip WHERE $__timeFilter(StartDate) and km_diff < 1000 and CarID = $Car and km_diff > 10) as avgTripKm\nFROM\n    (SELECT \n        (@rowid1:=@rowid1 + 1) firstSeq,\n            # chargingstate.ID AS EndId,\n            chargingstate.EndDate AS StartTrip,\n            charging.battery_level AS StartSOC,\n            charging.ideal_battery_range_km AS StartRange,\n            pos.odometer AS StartOdometer     ,\n            wh_tr\n    FROM\n        charging\n    INNER JOIN chargingstate ON charging.id = chargingstate.EndChargingID\n    INNER JOIN cars on chargingstate.carid = cars.id\n    INNER JOIN pos ON chargingstate.pos = pos.id\n    JOIN (SELECT @rowid1:=0) a\n    WHERE $__timeFilter(chargingstate.StartDate) and chargingstate.CarID = $Car  and\n        TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3  and chargingstate.EndChargingID - chargingstate.StartChargingID > 4\n    ORDER BY StartDate DESC) AS TEnd\n        JOIN\n    (SELECT \n        (@rowid2:=@rowid2 + 1) secondSeq,\n          #  chargingstate.ID AS StartId,\n            chargingstate.StartDate AS EndTrip,\n            charging.battery_level AS EndSOC,\n            charging.ideal_battery_range_km AS EndRange,\n            pos.odometer AS EndOdometer\n    FROM\n        charging\n    INNER JOIN chargingstate ON charging.id = chargingstate.StartChargingID\n    INNER JOIN pos ON chargingstate.pos = pos.id\n    JOIN (SELECT @rowid2:=0) a\n    WHERE $__timeFilter(chargingstate.StartDate) and chargingstate.CarID = $Car  and\n        TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3  and chargingstate.EndChargingID - chargingstate.StartChargingID > 4\n    ORDER BY StartDate DESC) AS TStart ON TEnd.firstSeq = TStart.secondSeq + 1\n    where (EndOdometer - StartOdometer between 5 and 1000) and ((EndOdometer - StartOdometer) / (StartSOC - EndSOC)) < 10 and StartSOC > EndSOC and EndOdometer - StartOdometer > 20\norder by StartTrip desc"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select \nsum(CO2_Mix)/1000 as \"CO2 kg mix\", sum(CO2_Mix) / (max(odometer) - min(odometer)) as \"CO2 g/km mix\",\nsum(CO2_Mix) / (max(odometer) - min(odometer)) / 10 / 2.37 as \"L gasoline / 100km\",\nsum(CO2_Mix) / (max(odometer) - min(odometer)) / 10 / 2.65 as \"L diesel / 100km\",\n(select sum(case when co2_g_kWh > 0 then null else charge_energy_added end) from chargingstate where $__timeFilter(chargingstate.StartDate) and chargingstate.CarId = $Car) as missingCO2kWh\nfrom\n(\nSELECT co2_g_kWh,  \n\tCASE WHEN meter_vehicle_kwh_sum > meter_utility_kwh_sum THEN (select 1-(meter_utility_kwh_sum / meter_vehicle_kwh_sum)) else 0 END as PV_percent,\n\tcharge_energy_added, \n    charge_energy_added * (1-(select PV_percent)) as Grid, \n    charge_energy_added * (select PV_percent) as PV,\n\t(select Grid) * co2_g_kWh as CO2_Grid,\n    charge_energy_added * co2_g_kWh as CO2_Mix,\n    odometer\n\tFROM chargingstate join pos on chargingstate.pos = pos.id\n\twhere $__timeFilter(chargingstate.StartDate) and TIMESTAMPDIFF(MINUTE, chargingstate.StartDate, chargingstate.EndDate) > 3 and chargingstate.EndChargingID - chargingstate.StartChargingID > 4\nand chargingstate.CarId = $Car and odometer > 0\n\t) T"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT   $__time(datum),  altitude as 'Höhe [m]'\r\nFROM  pos\r\nWHERE  $__timeFilter(datum) and CarID = $Car\r\nORDER BY  Datum ASC"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT speed div 10 * 10 as kmh, count(*) / (select count(*) from pos where $__timeFilter(datum) and CarID = $Car) as total\r\nFROM pos \r\nwhere $__timeFilter(datum) and CarID = $Car\r\ngroup by speed div 10 \r\nhaving kmh >= 10"
    }
   ]
  },
  {
   "title": "Charging Curves",
   "type": "xychart",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT chargingstate.id * 100 as color, address, charger_power, charging.battery_level\r\nFROM teslalogger.charging \r\njoin chargingstate on charging.id between StartChargingID and EndChargingID \r\njoin pos on chargingstate.Pos = pos.id\r\nWHERE charging.CarID=$Car and $__timeFilter(charging.Datum) and chargingstate.CarID = $Car and $__timeFilter(chargingstate.StartDate)\r\norder by chargingstate.id, charging.id"
    }
   ]
  }
 ]
}