{
 "title": "Status",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select \ncase\n  WHEN status = 1 then 'Sleep'\n  WHEN status = 2 then 'Online'\n  WHEN status = 3 then 'Offline'\n  WHEN status = 4 then 'Waking'\n  WHEN status = 5 then '?'\n  WHEN status = 6 then 'Driving'\n  WHEN status = 7 then 'Charging'\nend\n\nfrom (\nSELECT $__time(StartDate), \n(case \n\tWHEN state = 'asleep' then 1 \n\tWHEN state = 'online' then 2 \n    WHEN state = 'offline' then 3 \n    WHEN state = 'waking' then 4 \n    else 5 \nend) as status\nFROM state \nWHERE  \n$__timeFilter(startdate)\n\nunion\nSELECT $__time(StartDate), 6 as status FROM trip WHERE $__timeFilter(StartDate)\nunion \nSELECT $__time(EndDate), 2 as status FROM trip WHERE $__timeFilter(StartDate) and EndDate IS NOT NULL /* end of trip is online */\n\nunion\nSELECT $__time(StartDate), 7 as status FROM chargingstate WHERE $__timeFilter(StartDate) \nunion\nSELECT $__time(EndDate), 2 as status FROM chargingstate WHERE $__timeFilter(StartDate) and EndDate IS NOT NULL  /* end of charging is online */\n\norder by time_sec desc\n) as t1\nLimit 1\n"
    }
   ]
  },
  {
   "title": "SOC",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "select battery_level\r\nFROM\r\n(\r\nSELECT $__time(datum),battery_level\r\nFROM  pos\r\nWHERE  $__timeFilter(datum)\r\nunion\r\nSELECT $__time(datum),battery_level\r\nFROM  charging\r\nWHERE  $__timeFilter(datum)\r\norder by time_sec desc\r\n) as t1\r\nLimit 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Reichweite",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "select ideal_battery_range_km\r\nFROM\r\n(\r\nSELECT $__time(datum),ideal_battery_range_km\r\nFROM  pos\r\nWHERE  $__timeFilter(datum)\r\nunion\r\nSELECT $__time(datum),ideal_battery_range_km\r\nFROM  charging\r\nWHERE  $__timeFilter(datum)\r\norder by time_sec desc\r\n) as t1\r\nLimit 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Außentemperatur",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select outside_temp\r\nFROM\r\n(\r\nSELECT $__time(datum),outside_temp\r\nFROM  pos\r\nWHERE  $__timeFilter(datum)\r\nunion\r\nSELECT $__time(datum),outside_temp\r\nFROM  charging\r\nWHERE  $__timeFilter(datum)\r\norder by time_sec desc\r\n) as t1\r\nLimit 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Zelltemperatur",
   "type": "gauge",
   "description": "Nur verfügbar mit ScanMyTesla",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT val as 'Zelltemperatur'\nFROM can\nWHERE $__timeFilter(datum) and id = 2 and datum > \n(\n    SELECT $__time(StartDate)\n    FROM state \n    WHERE  \n    $__timeFilter(startdate)\n    \n    union\n    SELECT $__time(StartDate) FROM trip WHERE $__timeFilter(StartDate)\n    union \n    SELECT $__time(EndDate) FROM trip WHERE $__timeFilter(StartDate) and EndDate IS NOT NULL /* end of trip is online */\n    \n    union\n    SELECT $__time(StartDate) FROM chargingstate WHERE $__timeFilter(StartDate) \n    union\n    SELECT $__time(EndDate) FROM chargingstate WHERE $__timeFilter(StartDate) and EndDate IS NOT NULL  /* end of charging is online */\n    \n    order by time_sec desc\n    Limit 1\n)\nORDER BY datum DESC Limit 1"
    }
   ]
  },
  {
   "title": "km Stand",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT odometer\r\nFROM  pos\r\nWHERE  $__timeFilter(datum)\r\nORDER BY  id DESC \r\nLimit 1"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT $__time(StartDate), \n(case \n\tWHEN state = 'asleep' then 1 \n\tWHEN state = 'online' then 2 \n    WHEN state = 'offline' then 3 \n    WHEN state = 'waking' then 4 \n    else 5 \nend) as status\nFROM state \nWHERE  \n$__timeFilter(startdate)\n\nunion\nSELECT $__time(StartDate), 6 as status FROM trip WHERE $__timeFilter(StartDate)\nunion \nSELECT $__time(EndDate), 2 as status FROM trip WHERE $__timeFilter(StartDate) and EndDate IS NOT NULL /* end of trip is online */\n\nunion\nSELECT $__time(StartDate), 7 as status FROM chargingstate WHERE $__timeFilter(StartDate) \nunion\nSELECT $__time(EndDate), 2 as status FROM chargingstate WHERE $__timeFilter(StartDate) and EndDate IS NOT NULL  /* end of charging is online */\n\norder by time_sec desc\nLimit 1"
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 2 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT LEFT(version, CHAR_LENGTH(version) - LOCATE(' ', REVERSE(version))) as text FROM car_version order by id desc limit 1"
    }
   ]
  },
  {
   "title": "Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT $__time(StartDate), \n(case \n\tWHEN state = 'asleep' then 1 \n\tWHEN state = 'online' then 2 \n    WHEN state = 'offline' then 3 \n    WHEN state = 'waking' then 4 \n    else 5 \nend) as status\nFROM state \nWHERE  \n$__timeFilter(startdate)\n\nunion\nSELECT $__time(StartDate), 6 as status FROM trip WHERE $__timeFilter(StartDate)\nunion \nSELECT $__time(EndDate), 2 as status FROM trip WHERE $__timeFilter(StartDate) and EndDate IS NOT NULL /* end of trip is online */\n\nunion\nSELECT $__time(StartDate), 7 as status FROM chargingstate WHERE $__timeFilter(StartDate) \nunion\nSELECT $__time(EndDate), 2 as status FROM chargingstate WHERE $__timeFilter(StartDate) and EndDate IS NOT NULL  /* end of charging is online */\n\norder by time_sec\n"
    }
   ]
  }
 ]
}