on: push
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Build and Push to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: ./docker/webserver/Dockerfile
        tags: flipkill1985/webserver:latest, flipkill1985/webserver:${{ github.run_number }}
