# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET8 Base Image

on:
  workflow_dispatch:
  
jobs:
  build:
    if: github.ref == 'refs/heads/NET8'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git describe tags
      shell: bash
      run: |
        git describe --tags --abbrev=0

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: bassmaster187
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push Teslalogger-Base Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile-Base
        push: true
        tags: |
          bassmaster187/teslalogger-base:latest
          bassmaster187/teslalogger-base:1.0.0
        platforms: linux/amd64,linux/arm64

